### ISSUE TITLE
move old scripts out? link EDI DOI in README

### ISSUE THREAD

**Issue by plzmsu** [aquaXterra/freshwater_insects_CONUS#1]
@ltwardoch @billspat I think these files should be moved outside of https://github.com/aquaXterra/freshwater_insects_CONUS because this repo is linked in the data paper, and these are extra scripts, plus they are based on old versions of the database so I’m not sure they would even run. 

https://github.com/aquaXterra/freshwater_insects_CONUS/blob/master/Fresh_traits_5_11_18.R

https://github.com/aquaXterra/freshwater_insects_CONUS/tree/master/code/exploratory

I also think we should include the EDI DOI and the full GEB citation in the README for this repo. Agree?

**Comment by ltwardoch** [comment]
All of the files should be moved out except for the read me, templates, and the Data_cleaning_WQP_traits folder. Have they been moved? If so, I can delete them and add the EDI DOI and GEB citation.

**Comment by plzmsu** [comment]
files moved to GDrive - see commit 54e85232c225d1ef48033c00a90dae52be2c49fd.

Updated README
